name: publish npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Print registry URL and package name
        run: |
          echo "Registry URL: https://registry.npmjs.org/"
          echo "Package name: $(jq -r .name < package.json)"
      - name: Authenticate to GitHub Package Registry
        run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN}}
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - run: echo "@codingdud:registry=https://registry.npmjs.org/" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        run: npm publish --access public
      - run: echo ${{secrets.NPM_AUTH_TOKEN}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
