name: Publish Package to npmjs
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: JS-DevTools/npm-publish@v3
        id: publish
        with:
          token: ${{secrets.NPM_AUTH_TOKEN}}
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm publish
      - run: echo ${{secrets.NPM_AUTH_TOKEN}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}